# Admin Routes
admin_aimodulemaker_dashboard:
    path: aimodulemaker/dashboard
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::dashboardAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
        _legacy_link: 'AdminArtAiModuleMaker'

admin_aimodulemaker_list:
    path: aimodulemaker/modules
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleListController::listAction'
        _legacy_controller: 'AdminArtAiModuleList'
        _legacy_link: 'AdminArtAiModuleList'

admin_aimodulemaker_create:
    path: aimodulemaker/create
    methods: [GET, POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::createAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
        _legacy_link: 'AdminArtAiModuleMaker'

admin_aimodulemaker_edit:
    path: aimodulemaker/edit/{id}
    methods: [GET, POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::editAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
        _legacy_link: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_delete:
    path: aimodulemaker/delete/{id}
    methods: [POST, DELETE]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::deleteAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
        _legacy_link: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_settings:
    path: aimodulemaker/settings
    methods: [GET, POST]
    defaults:
        _controller: 'AdminArtAiSettingsController::indexAction'
        _legacy_controller: 'AdminArtAiSettings'
        _legacy_link: 'AdminArtAiSettings'

# API Routes
admin_aimodulemaker_ai_chat:
    path: aimodulemaker/api/chat
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::aiChatAction'
        _legacy_controller: 'AdminArtAiModuleMaker'

admin_aimodulemaker_generate_code:
    path: aimodulemaker/api/generate
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::generateCodeAction'
        _legacy_controller: 'AdminArtAiModuleMaker'

admin_aimodulemaker_analyze_code:
    path: aimodulemaker/api/analyze
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::analyzeCodeAction'
        _legacy_controller: 'AdminArtAiModuleMaker'

# File Management Routes
admin_aimodulemaker_files:
    path: aimodulemaker/files/{id}
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::filesAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_file_content:
    path: aimodulemaker/file/{id}/{path}
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::fileContentAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'
        path: '.+'

admin_aimodulemaker_save_file:
    path: aimodulemaker/file/save/{id}/{path}
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::saveFileAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'
        path: '.+'

# Version Management Routes
admin_aimodulemaker_versions:
    path: aimodulemaker/versions/{id}
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::versionsAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_create_version:
    path: aimodulemaker/version/create/{id}
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::createVersionAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

# GitHub Integration Routes
admin_aimodulemaker_github_sync:
    path: aimodulemaker/github/sync/{id}
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::githubSyncAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_github_webhook:
    path: aimodulemaker/github/webhook
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::githubWebhookAction'
        _legacy_controller: 'AdminArtAiModuleMaker'

# Export/Import Routes
admin_aimodulemaker_export:
    path: aimodulemaker/export/{id}
    methods: [GET]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::exportAction'
        _legacy_controller: 'AdminArtAiModuleMaker'
    requirements:
        id: '\d+'

admin_aimodulemaker_import:
    path: aimodulemaker/import
    methods: [POST]
    defaults:
        _controller: 'AdminArtAiModuleMakerController::importAction'
        _legacy_controller: 'AdminArtAiModuleMaker'