services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # Controllers
    PrestaShop\Module\ArtAimodulemaker\Controller\Admin\:
        resource: '../controllers/admin/*'
        exclude: '../controllers/admin/index.php'

    PrestaShop\Module\ArtAimodulemaker\Controller\Front\:
        resource: '../controllers/front/*'
        exclude: '../controllers/front/index.php'
        
    # Repositories
    PrestaShop\Module\ArtAimodulemaker\Repository\:
        resource: '../classes/Database/*Repository.php'
        
    # AI Handlers
    PrestaShop\Module\ArtAimodulemaker\AiHandler\:
        resource: '../classes/AiHandler/*Handler.php'
        
    # Git Handlers
    PrestaShop\Module\ArtAimodulemaker\GitHandler\:
        resource: '../classes/GitHandler/*Handler.php'
        
    # Module Builder
    PrestaShop\Module\ArtAimodulemaker\ModuleBuilder\:
        resource: '../classes/ModuleBuilder/*.php'

    # Specific Services
    prestashop.module.art_aimodulemaker.module_builder:
        class: PrestaShop\Module\ArtAimodulemaker\ModuleBuilder\ModuleGenerator
        arguments:
            $fileGenerator: '@prestashop.module.art_aimodulemaker.file_generator'
            $validator: '@prestashop.module.art_aimodulemaker.validation_handler'
            
    prestashop.module.art_aimodulemaker.file_generator:
        class: PrestaShop\Module\ArtAimodulemaker\ModuleBuilder\FileGenerator
        
    prestashop.module.art_aimodulemaker.validation_handler:
        class: PrestaShop\Module\ArtAimodulemaker\ModuleBuilder\ValidationHandler
        
    prestashop.module.art_aimodulemaker.openai_handler:
        class: PrestaShop\Module\ArtAimodulemaker\AiHandler\OpenAiHandler
        arguments:
            $apiRepository: '@prestashop.module.art_aimodulemaker.api_repository'
            
    prestashop.module.art_aimodulemaker.claude_handler:
        class: PrestaShop\Module\ArtAimodulemaker\AiHandler\ClaudeHandler
        arguments:
            $apiRepository: '@prestashop.module.art_aimodulemaker.api_repository'
            
    prestashop.module.art_aimodulemaker.github_handler:
        class: PrestaShop\Module\ArtAimodulemaker\GitHandler\GitHubHandler
        arguments:
            $apiRepository: '@prestashop.module.art_aimodulemaker.api_repository'
            $moduleRepository: '@prestashop.module.art_aimodulemaker.module_repository'
            
    # Repositories as Services
    prestashop.module.art_aimodulemaker.api_repository:
        class: PrestaShop\Module\ArtAimodulemaker\Repository\ApiKeyRepository
        
    prestashop.module.art_aimodulemaker.module_repository:
        class: PrestaShop\Module\ArtAimodulemaker\Repository\ModuleRepository
        
    prestashop.module.art_aimodulemaker.version_repository:
        class: PrestaShop\Module\ArtAimodulemaker\Repository\VersionRepository

    # Event Subscribers
    prestashop.module.art_aimodulemaker.module_subscriber:
        class: PrestaShop\Module\ArtAimodulemaker\Event\ModuleSubscriber
        tags:
            - { name: kernel.event_subscriber }
            
    prestashop.module.art_aimodulemaker.github_subscriber:
        class: PrestaShop\Module\ArtAimodulemaker\Event\GitHubSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # Cache Services
    prestashop.module.art_aimodulemaker.cache.file_cache:
        class: PrestaShop\Module\ArtAimodulemaker\Cache\FileCache
        arguments:
            $cacheDir: '%kernel.cache_dir%/art_aimodulemaker'
            
    prestashop.module.art_aimodulemaker.cache.api_cache:
        class: PrestaShop\Module\ArtAimodulemaker\Cache\ApiCache
        arguments:
            $cacheService: '@prestashop.module.art_aimodulemaker.cache.file_cache'
            
    # Security Services
    prestashop.module.art_aimodulemaker.security.api_authenticator:
        class: PrestaShop\Module\ArtAimodulemaker\Security\ApiAuthenticator
        arguments:
            $apiRepository: '@prestashop.module.art_aimodulemaker.api_repository'
            
    prestashop.module.art_aimodulemaker.security.token_generator:
        class: PrestaShop\Module\ArtAimodulemaker\Security\TokenGenerator
        arguments:
            $secret: '%kernel.secret%'

    # Utility Services
    prestashop.module.art_aimodulemaker.utils.file_manager:
        class: PrestaShop\Module\ArtAimodulemaker\Utils\FileManager
        arguments:
            $moduleDir: '%kernel.project_dir%/modules/art_aimodulemaker'
            
    prestashop.module.art_aimodulemaker.utils.code_analyzer:
        class: PrestaShop\Module\ArtAimodulemaker\Utils\CodeAnalyzer
        
    prestashop.module.art_aimodulemaker.utils.template_renderer:
        class: PrestaShop\Module\ArtAimodulemaker\Utils\TemplateRenderer
        arguments:
            $twig: '@twig'

    # Export/Import Services
    prestashop.module.art_aimodulemaker.export.module_exporter:
        class: PrestaShop\Module\ArtAimodulemaker\Export\ModuleExporter
        arguments:
            $fileManager: '@prestashop.module.art_aimodulemaker.utils.file_manager'
            
    prestashop.module.art_aimodulemaker.export.module_importer:
        class: PrestaShop\Module\ArtAimodulemaker\Export\ModuleImporter
        arguments:
            $fileManager: '@prestashop.module.art_aimodulemaker.utils.file_manager'
            $moduleRepository: '@prestashop.module.art_aimodulemaker.module_repository'

    # Logger Services
    prestashop.module.art_aimodulemaker.logger.module_logger:
        class: PrestaShop\Module\ArtAimodulemaker\Logger\ModuleLogger
        arguments:
            $logDir: '%kernel.logs_dir%/art_aimodulemaker'